-- Dashboard principal : remplace mainnetwork / reportingdimension / distributionchannel
-- par businessmodel1 / businessmodel2, suite a la refonte du meme nom sur la dimension
-- cube SEI_X3_LCS.LCS_CUSTOMER (BUSINESS_MODEL_1 / BUSINESS_MODEL_2).
--
-- A executer sur le SEI Cube (_DEV et prod), puis relancer les commandes de refresh
-- du Dashboard principal.
--
-- Script idempotent : le relancer ne provoque aucune erreur.

-- ============================================================================
-- INTRANET_SALES_DAILY
-- ============================================================================

IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY', 'mainnetwork') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY DROP COLUMN mainnetwork;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY', 'distributionchannel') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY DROP COLUMN distributionchannel;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY', 'businessmodel1') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY ADD businessmodel1 VARCHAR(100) NULL;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY ADD businessmodel2 VARCHAR(100) NULL;
GO

IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY_DEV', 'mainnetwork') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY_DEV DROP COLUMN mainnetwork;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY_DEV', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY_DEV DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY_DEV', 'distributionchannel') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY_DEV DROP COLUMN distributionchannel;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY_DEV', 'businessmodel1') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY_DEV ADD businessmodel1 VARCHAR(100) NULL;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_DAILY_DEV', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_DAILY_DEV ADD businessmodel2 VARCHAR(100) NULL;
GO

-- ============================================================================
-- INTRANET_SALES_AGG_YEAR
-- ============================================================================

IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR', 'mainnetwork') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR DROP COLUMN mainnetwork;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR', 'distributionchannel') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR DROP COLUMN distributionchannel;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR', 'businessmodel1') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR ADD businessmodel1 VARCHAR(100) NULL;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR ADD businessmodel2 VARCHAR(100) NULL;
GO

IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV', 'mainnetwork') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV DROP COLUMN mainnetwork;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV', 'distributionchannel') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV DROP COLUMN distributionchannel;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV', 'businessmodel1') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV ADD businessmodel1 VARCHAR(100) NULL;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_YEAR_DEV ADD businessmodel2 VARCHAR(100) NULL;
GO

-- ============================================================================
-- INTRANET_SALES_AGG_MONTH
-- ============================================================================

IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH', 'mainnetwork') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH DROP COLUMN mainnetwork;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH', 'distributionchannel') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH DROP COLUMN distributionchannel;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH', 'businessmodel1') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH ADD businessmodel1 VARCHAR(100) NULL;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH ADD businessmodel2 VARCHAR(100) NULL;
GO

IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV', 'mainnetwork') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV DROP COLUMN mainnetwork;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV', 'distributionchannel') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV DROP COLUMN distributionchannel;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV', 'businessmodel1') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV ADD businessmodel1 VARCHAR(100) NULL;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_SALES_AGG_MONTH_DEV ADD businessmodel2 VARCHAR(100) NULL;
GO

-- ============================================================================
-- INTRANET_BACKLOG_CLI
--
-- Cette table n'a pas la meme source que les trois precedentes : sa colonne
-- reportingdimension vient du dictionnaire X3 brut (ATABDIV, IDENT1_0='32'),
-- qui porte deja les nouveaux libelles business model sans avoir change de nom.
-- Simple renommage donc, pas de reconstruction de donnees.
-- La colonne mainnetwork existante n'est jamais alimentee : laissee inchangee.
-- ============================================================================

IF COL_LENGTH('MASTER_TABLES.INTRANET_BACKLOG_CLI', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_BACKLOG_CLI DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_BACKLOG_CLI', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_BACKLOG_CLI ADD businessmodel2 VARCHAR(100) NULL;
GO

IF COL_LENGTH('MASTER_TABLES.INTRANET_BACKLOG_CLI_DEV', 'reportingdimension') IS NOT NULL
    ALTER TABLE MASTER_TABLES.INTRANET_BACKLOG_CLI_DEV DROP COLUMN reportingdimension;
GO
IF COL_LENGTH('MASTER_TABLES.INTRANET_BACKLOG_CLI_DEV', 'businessmodel2') IS NULL
    ALTER TABLE MASTER_TABLES.INTRANET_BACKLOG_CLI_DEV ADD businessmodel2 VARCHAR(100) NULL;
GO
