SELECT
    SOH.BPCCRYNAM_0 AS PAYS,
    SOH.STOFCY_0    AS SITE,
    ATX.TEXTE_0     AS MAINNETWORK,
    SOH.BPCINV_0    AS CLIENT,
    BPC_INV.BPCNAM_0 AS NOM_CLIENT,
    SOH.BPCORD_0    AS CLIENT_COMMANDE,
    SOH.BPCNAM_0    AS NOM_CLIENT_COMMANDE,
    SOH.PTE_0       AS PAIEMENT,
    SOQ.SOHNUM_0    AS NUM_COMMANDE,
    CASE WHEN SOH.CUSORDREF_0 <> '' THEN SOH.CUSORDREF_0 ELSE SOH.ZNORIGIN_0 END AS REF_CLIENT,
    SOH.ZNORIGIN_0  AS REFERENCE_INTERNE,
    ITM.TSICOD_0    AS GENRE,
    ATX5.TEXTE_0 AS AGE,
    SOH.BPAADD_0    AS ADRESSE_LIVRAISON,
    ITM.TCLCOD_0    AS FAMILLE,
    SOQ.YCOLLECT_0  AS COLLECTION,
    ITM.ITMREF_0    AS SKU,
    SPLIT.ARTICLE_BASE AS ARTICLE,
    SPLIT.VARIANT_VAL  AS VARIANT,
    ITM.ITMDES1_0,
    ITM.EANCOD_0    AS EAN,
    CASE WHEN ITC.ZDROPPED_0 = 2 THEN 'OUI' ELSE 'NON' END AS DROPPE,
    ATX6.TEXTE_0    AS GROUP_CODE,
    CONVERT(varchar(10), SOH.ORDDAT_0, 23)    AS DATE_COMMANDE,
    CONVERT(varchar(10), SOQ.DEMDLVDAT_0, 23) AS DATE_LIVRAISON,
    REP2.REPNAM_0   AS REP1,
    REP1.REPNAM_0   AS REP2,
    ITM.ITMSTA_0    AS STATUT_ARTICLE,
    CAST(ROUND(SOQ.QTY_0 - (SOQ.DLVQTY_0 + SOQ.ODLQTY_0), 0) AS INT) AS QUANTITE,
    ISNULL(PO.PO_EN_COURS, 0) AS PO_EN_COURS,
    SOH.CUR_0,
    SOP.NETPRINOT_0 AS PRICE_HT,
    SOP.DISCRGVAL1_0 AS REMISE_AUTO,
    SOP.DISCRGVAL2_0 AS REMISE_MANU,
    ISNULL(SVT.DTAAMT_0, 0) AS REMISE_GLOBAL,
    SOH.BPDNAM_0    AS CLIENT_LIVRE,
    ATX4.TEXTE_0    AS INDEPENDANT_GROUPMENT,
    BPA.POSCOD_0    AS CODE_POSTAL,
    BPA.CTY_0       AS VILLE,
    SOH.ZCLASSE_0,
    NULL AS STOCK
FROM X3_LCS.SORDERQ SOQ
         INNER JOIN X3_LCS.SORDER SOH ON SOQ.SOHNUM_0 = SOH.SOHNUM_0
         INNER JOIN X3_LCS.SORDERP SOP ON SOQ.SOHNUM_0 = SOP.SOHNUM_0 AND SOQ.ITMREF_0 = SOP.ITMREF_0 AND SOQ.SOPLIN_0 = SOP.SOPLIN_0
         INNER JOIN X3_LCS.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0
    CROSS APPLY (
    SELECT
        CASE WHEN CHARINDEX('_', ITM.ITMREF_0) > 0
             THEN LEFT(ITM.ITMREF_0, CHARINDEX('_', ITM.ITMREF_0) - 1)
             ELSE ITM.ITMREF_0
        END AS ARTICLE_BASE,
        CASE WHEN CHARINDEX('_', ITM.ITMREF_0) > 0
             THEN SUBSTRING(ITM.ITMREF_0, CHARINDEX('_', ITM.ITMREF_0) + 1, 50)
             ELSE NULL
        END AS VARIANT_VAL
) AS SPLIT
INNER JOIN X3_LCS.BPCUSTOMER BPC ON SOH.BPCORD_0 = BPC.BPCNUM_0
    LEFT  JOIN X3_LCS.BPCUSTOMER BPC_INV ON SOH.BPCINV_0 = BPC_INV.BPCNUM_0
    INNER JOIN X3_LCS.BPADDRESS BPA ON BPC.BPCNUM_0 = BPA.BPANUM_0 AND BPA.BPAADD_0 = SOH.BPAADD_0
    LEFT  JOIN X3_LCS.SALESREP REP1 ON BPC.REP_0 = REP1.REPNUM_0
    LEFT  JOIN X3_LCS.SALESREP REP2 ON BPC.REP_1 = REP2.REPNUM_0
    LEFT  JOIN X3_LCS.ATEXTRA ATX  ON ATX.IDENT2_0  = BPC.TSCCOD_2     AND ATX.CODFIC_0  = 'ATABDIV' AND ATX.LANGUE_0  = 'FRA' AND ATX.ZONE_0  = 'LNGDES' AND ATX.IDENT1_0  = '32'
    LEFT  JOIN X3_LCS.ATEXTRA ATX4 ON ATX4.IDENT2_0 = BPC.ZGROUPIND_0 AND ATX4.CODFIC_0 = 'ATABDIV' AND ATX4.LANGUE_0 = 'FRA' AND ATX4.ZONE_0 = 'LNGDES' AND ATX4.IDENT1_0 = '6021'
    LEFT  JOIN X3_LCS.ATEXTRA ATX5 ON ATX5.CODFIC_0 = 'TABLINCFG' AND ATX5.LANGUE_0 = 'FRA' AND ATX5.IDENT1_0 = ITM.CFGLIN_0
    LEFT  JOIN X3_LCS.ZITMCOL  ITC ON ITC.ITMREF_0 = SPLIT.ARTICLE_BASE AND ITC.YCOLLECT_0 = SOQ.YCOLLECT_0
    LEFT  JOIN X3_LCS.ATEXTRA ATX6 ON ATX6.IDENT2_0 = BPC.ZGRPCOD_0 AND ATX6.CODFIC_0 = 'ATABDIV' AND ATX6.LANGUE_0 = 'FRA' AND ATX6.ZONE_0 = 'LNGDES' AND ATX6.IDENT1_0 = '6028'
    LEFT  JOIN (
        SELECT POQ.ITMREF_0, POQ.PRHFCY_0,
               SUM(POQ.QTYUOM_0 - POQ.RCPQTYSTU_0) AS PO_EN_COURS
        FROM X3_LCS.PORDERQ POQ
        INNER JOIN X3_LCS.PORDER POH ON POQ.POHNUM_0 = POH.POHNUM_0
        WHERE POQ.LINCLEFLG_0 = 1 AND POH.BETFCY_0 <> 2
        GROUP BY POQ.ITMREF_0, POQ.PRHFCY_0
    ) PO ON PO.ITMREF_0 = SOQ.ITMREF_0 AND PO.PRHFCY_0 = SOH.STOFCY_0
    LEFT  JOIN X3_LCS.SVCRFOOT SVT ON SOH.SOHNUM_0 = SVT.VCRNUM_0 AND SVT.DTA_0 = 1
WHERE
    SOQ.SOQSTA_0 <> 3
  AND SOH.ZSOHVALSTA_0 <> 3 -- Brouillon
  AND BPC.BCGCOD_0 <> 'INTER'
    {{WHERE_CLAUSE}}
{{ORDER_BY}}
{{PAGINATION}}
