SELECT
    SOH.BPCCRYNAM_0 AS PAYS,
    SOH.STOFCY_0 AS SITE,
    ATX.TEXTE_0 AS MAINNETWORK,
    SOH.BPCINV_0 AS CLIENT,
    BPC_INV.BPCNAM_0 AS NOM_CLIENT,
    SOH.BPCORD_0 AS CLIENT_COMMANDE,
    SOH.BPCNAM_0 AS NOM_CLIENT_COMMANDE,
    SOH.PTE_0 AS PAIEMENT,
    SOQ.SOHNUM_0 AS NUM_COMMANDE,
    SOH.CUSORDREF_0 AS REF_CLIENT,
    ITM.TSICOD_0 AS CODE_MARQUE,
    SOH.BPAADD_0 AS ADRESSE_LIVRAISON,
    ITM.TCLCOD_0 AS FAMILLE,
    SOH.ZCOLLECT_0 AS COLLECTION,
    SOQ.ITMREF_0 AS ARTICLE,
    ITM.ITMDES1_0,
    ITM.EANCOD_0 AS EAN,
    CONVERT(varchar(10), SOH.ORDDAT_0, 23) AS DATE_COMMANDE,
    CONVERT(varchar(10), SOQ.DEMDLVDAT_0, 23) AS DATE_LIVRAISON,
    REP2.REPNAM_0 AS REP1,
    REP1.REPNAM_0 AS REP2,
    ITM.ITMSTA_0 AS STATUT_ARTICLE,
    (SOQ.QTY_0 - (SOQ.DLVQTY_0 + SOQ.ODLQTY_0)) AS QUANTITE,
    SOH.CUR_0,
    SOP.NETPRINOT_0 AS PRICE_HT,
    SOH.BPDNAM_0 AS CLIENT_LIVRE,
    ATX4.TEXTE_0        AS INDEPENDANT_GROUPMENT,
    BPA.CTY_0           AS VILLE,
    SOH.ZCLASSE_0,
    NULL AS STOCK

FROM X3_LCS.SORDERQ SOQ
         INNER JOIN X3_LCS.SORDER SOH ON SOQ.SOHNUM_0 = SOH.SOHNUM_0
         INNER JOIN X3_LCS.SORDERP SOP ON SOQ.SOHNUM_0 = SOP.SOHNUM_0 AND SOQ.ITMREF_0 = SOP.ITMREF_0 AND SOQ.SOPLIN_0 = SOP.SOPLIN_0
         INNER JOIN X3_LCS.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0
         INNER JOIN X3_LCS.BPCUSTOMER BPC ON SOH.BPCORD_0 = BPC.BPCNUM_0
         LEFT JOIN X3_LCS.BPCUSTOMER BPC_INV ON SOH.BPCINV_0 = BPC_INV.BPCNUM_0
         INNER JOIN X3_LCS.BPADDRESS BPA ON BPC.BPCNUM_0 = BPA.BPANUM_0 AND BPA.BPAADD_0 = SOH.BPAADD_0
         LEFT JOIN X3_LCS.SALESREP REP1 ON BPC.REP_0 = REP1.REPNUM_0
         LEFT JOIN X3_LCS.SALESREP REP2 ON BPC.REP_1 = REP2.REPNUM_0
         LEFT JOIN X3_LCS.ATEXTRA ATX ON ATX.IDENT2_0 = BPC.TSCCOD_2 AND ATX.CODFIC_0 = 'ATABDIV' AND ATX.LANGUE_0 = 'FRA' AND ATX.ZONE_0 = 'LNGDES' AND ATX.IDENT1_0 = '32'
         LEFT JOIN X3_LCS.ATEXTRA ATX4 ON ATX4.IDENT2_0 = BPC.ZGROUPIND_0 AND ATX4.CODFIC_0 = 'ATABDIV' AND ATX4.LANGUE_0 = 'FRA' AND ATX4.ZONE_0 = 'LNGDES' AND ATX4.IDENT1_0 = '6021'

WHERE
    SOQ.SOQSTA_0 <> 3
    AND BPC.BCGCOD_0 <> 'INTER'
