SELECT
    POH.BPSNUM_0,
    POH.BPRNAM_0,
    POH.YCOLLECTION_0 AS COLLECTION,
    ITM.TCLCOD_0 AS FAMILLE,
    POH.POHNUM_0,
    POQ.PRHFCY_0,
    CONVERT(varchar(10), POH.ORDDAT_0, 23) AS ORDDAT_0,
    POQ.ITMREF_0,
    ITM.ITMDES1_0,
    CASE WHEN ITC.ZDROPPED_0 = 2 THEN 'OUI' ELSE 'NON' END AS DROPPE,
    POQ.ITMREFBPS_0,
    POQ.QTYUOM_0,
    POQ.RCPQTYSTU_0,
    CONVERT(varchar(10), POQ.EXTRCPDAT_0, 23) AS EXTRCPDAT_0,
    POQ.LINCLEFLG_0,
    POH.ORDREF_0,
    NULL AS XSHIPDAT_0,
    POP.NETPRI_0,
    POQ.LINAMT_0,
    POH.CUR_0,
    ITM.TSICOD_0,
    CASE WHEN POH.ZVALIDE_0 = 2 THEN 'OUI' ELSE 'NON' END AS VALIDE,
    ATX.TEXTE_0 AS MDL_0
FROM X3_LCS.PORDER POH
         INNER JOIN X3_LCS.PORDERQ POQ ON POH.POHNUM_0 = POQ.POHNUM_0
         INNER JOIN X3_LCS.PORDERP POP ON POQ.POHNUM_0 = POP.POHNUM_0 AND POQ.POPLIN_0 = POP.POPLIN_0
         INNER JOIN X3_LCS.ITMMASTER ITM ON POQ.ITMREF_0 = ITM.ITMREF_0
         LEFT JOIN X3_LCS.ATEXTRA ATX ON POH.MDL_0 = ATX.IDENT1_0 AND ATX.LANGUE_0 = 'FRA' AND ATX.CODFIC_0 = 'TABMODELIV' AND ZONE_0 = 'SHOAXX'
         LEFT JOIN X3_LCS.ZITMCOL  ITC ON LEFT(ITM.ITMREF_0, CHARINDEX('_', ITM.ITMREF_0 + '_') - 1) = ITC.ITMREF_0 AND ITC.YCOLLECT_0 = POH.YCOLLECTION_0
WHERE
    POQ.LINCLEFLG_0 = 1
  AND POH.BETFCY_0 <> 2;
