SELECT
    SOH.BPCCRYNAM_0 AS PAYS,
    SOH.STOFCY_0 AS SITE,
    SOH.BPCORD_0 AS CLIENT,
    SOH.BPCNAM_0 AS NOM_CLIENT,
    SOH.PTE_0 AS PAIEMENT,
    SOQ.SOHNUM_0 AS NUM_COMMANDE,
    SOH.CUSORDREF_0 AS REF_CLIENT,
    ITM.TSICOD_0 AS CODE_MARQUE,
    SOH.BPAADD_0 AS ADRESSE_LIVRAISON,
    ITM.TCLCOD_0 AS FAMILLE,
    SOQ.ZCOLLECT_0 AS COLLECTION,
    SOQ.ITMREF_0 AS ARTICLE,
    ITM.ITMDES1_0,
    ITM.EANCOD_0 AS EAN,
    SOH.ORDDAT_0 AS DATE_COMMANDE,
    SOQ.DEMDLVDAT_0 AS DATE_LIVRAISON,
    SOH.REP_0 AS REPRESENTANT,
    ITM.ITMSTA_0 AS STATUT_ARTICLE,
    (SOQ.QTY_0 - (SOQ.DLVQTY_0 + SOQ.ODLQTY_0)) AS QUANTITE,
    SOH.CUR_0,
    SOP.NETPRINOT_0 AS PRICE_HT,
    SOH.BPDNAM_0 AS CLIENT_LIVRE,
    NULL AS STOCK

FROM X3_LCS.SORDERQ SOQ
         INNER JOIN X3_LCS.SORDER SOH ON SOQ.SOHNUM_0 = SOH.SOHNUM_0
         INNER JOIN X3_LCS.SORDERP SOP ON SOQ.SOHNUM_0 = SOP.SOHNUM_0 AND SOQ.ITMREF_0 = SOP.ITMREF_0 AND SOQ.SOPLIN_0 = SOP.SOPLIN_0
         INNER JOIN X3_LCS.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0
WHERE
    SOQ.SOQSTA_0 <> 3;
