SELECT
    CI.SITE_EXPEDITION,
    CI.SITE_RECEPTION,
    CI.TYPE_FLUX,
    CI.COLLECTION,
    CI.FAMILLE,
    CI.ITMREF_0    AS ARTICLE,
    CI.DESIGNATION,
    CI.DROPPE,
    CASE WHEN ITM.ZNOOSFLG_0 = 2 THEN 'Oui' ELSE 'Non' END AS NOOS,
    CI.BPSNUM_0    AS CODE_FOURNISSEUR,
    CI.BPRNAM_0,
    CI.NO_DOCUMENT,
    CONVERT(varchar(10), CI.ORDDAT_0, 23) AS DATE_COMMANDE,
    CONVERT(varchar(10), CI.XSHIPDAT_0, 23)  AS DATE_EXPEDITION,
    CONVERT(varchar(10), CI.EXTRCPDAT_0, 23) AS DATE_LIVRAISON,
    CI.ORDREF_0    AS REF_INTERNE,
    CI.QTE_RESTANTE,
    CI.VALORISATION_UNITAIRE AS PRIX,
    CI.CUR_0       AS DEVISE,
    CI.MDL_0,
    CI.VALIDE
FROM MASTER_TABLES.COMMANDES_INTERSITES CI
    LEFT JOIN X3_LCS.ITMMASTER ITM ON ITM.ITMREF_0 = CI.ITMREF_0
