SELECT POH.BPSNUM_0, POH.POHNUM_0, POQ.PRHFCY_0, CONVERT(varchar(10), POH.ORDDAT_0, 23) AS ORDDAT_0, POQ.ITMREF_0, POQ.ITMREFBPS_0, POQ.QTYUOM_0,
       POQ.RCPQTYSTU_0, CONVERT(varchar(10), POQ.EXTRCPDAT_0, 23) AS EXTRCPDAT_0, POQ.LINCLEFLG_0, POH.ORDREF_0, NULL AS XSHIPDAT_0, POP.NETPRI_0, POQ.LINAMT_0, POH.CUR_0, ITM.TSICOD_0,
       CASE WHEN POH.ZVALIDE_0 = 2 THEN 'OUI' ELSE 'NON' END AS VALIDE, POH.MDL_0 AS MDL_0
FROM X3_LCS.PORDER AS POH, X3_LCS.PORDERQ AS POQ, X3_LCS.PORDERP AS POP, X3_LCS.ITMMASTER as ITM
WHERE POH.POHNUM_0 = POQ.POHNUM_0
  AND POQ.POHNUM_0 = POP.POHNUM_0
  AND POQ.POPLIN_0 = POP.POPLIN_0
  AND POQ.ITMREF_0 = ITM.ITMREF_0
  AND POQ.LINCLEFLG_0 = 1
  AND POH.BETFCY_0 <> 2;
