SELECT
    REPLACE(C.ITEMGROUPCODE, '-', '') AS ITEMGROUPCODE,
    C.ITEM_ID                         AS ARTICLE,
    SUM(I.QUANTITY)                   AS QUANTITY,
    SUM(I.AMOUNTEURTM)                AS CA
FROM SEI_X3_LCS.LCS_COLLECTION C
         LEFT JOIN SEI_X3_LCS.CONSO_INVOICES I
                   ON I.ITEMNO    = C.ITEM_ID
                   AND I.SERIESNO = C.SERIESCODE
WHERE
    I.ISBOHPERIMETERPRODUCT = 1
  AND I.DOCUMENTTYPE IN ('INVOICE', 'CREDITMEMO')
  AND C.ITEMFAMILYCODE IN ('FTW', 'APL')
  AND I.COMPANYCODE = 'LCSI'
  AND C.SERIESCODE >= '2023-01-SS'
  AND I.VARIANTCODE <> 'SPL'
    {{COLLECTION_WHERE}}
    {{FAMILY_WHERE}}
GROUP BY
    REPLACE(C.ITEMGROUPCODE, '-', ''),
    C.ITEM_ID
