SELECT TOP 10
    'https://www.lecoqsportif.com/cdn/shop/files/' + I.ITEMNO + '_2.jpg' AS PHOTO,
    C.ITEMFAMILYCODE AS FAMILY,
       CASE
           WHEN C.AGEGROUP = 'ADULT' THEN C.GENUSCODE
           ELSE 'KIDS'
           END AS TYPE,
       I.ITEMNO AS ARTICLE,
       C.ITEMDESC AS DESCRIPTION,
       SUM(I.QUANTITY) AS QUANTITY
FROM SEI_X3_LCS.LCS_COLLECTION C
         LEFT JOIN SEI_X3_LCS.CONSO_INVOICES I
                   ON I.ITEMNO = C.ITEM_ID
                       AND I.SERIESNO = C.SERIESCODE
WHERE
    I.ISBOHPERIMETERPRODUCT = 1
  AND I.DOCUMENTTYPE IN ('INVOICE', 'CREDITMEMO')
  AND C.ITEMFAMILYCODE IN ('FTW', 'APL')
  AND I.COMPANYCODE = 'LCSI'
  AND C.SERIESCODE >= '2023-01-SS'
  AND I.VARIANTCODE <> 'SPL'
    {{COLLECTION_WHERE}}
    {{FAMILY_WHERE}}
    {{TYPE_WHERE}}
GROUP BY
    I.ITEMNO,
    C.ITEMDESC,
    C.ITEMFAMILYCODE,
    CASE
    WHEN C.AGEGROUP = 'ADULT' THEN C.GENUSCODE
    ELSE 'KIDS'
END
ORDER BY
    SUM(I.QUANTITY) DESC;
