SELECT COUNT(*) AS TOTAL
FROM X3_LCS.SORDERQ SOQ
INNER JOIN X3_LCS.SORDER  SOH ON SOQ.SOHNUM_0 = SOH.SOHNUM_0
INNER JOIN X3_LCS.SORDERP SOP
        ON SOQ.SOHNUM_0 = SOP.SOHNUM_0
       AND SOQ.ITMREF_0 = SOP.ITMREF_0
       AND SOQ.SOPLIN_0 = SOP.SOPLIN_0
INNER JOIN X3_LCS.ITMMASTER ITM ON SOQ.ITMREF_0 = ITM.ITMREF_0

CROSS APPLY (
    SELECT
        CASE WHEN CHARINDEX('_', ITM.ITMREF_0) > 0
             THEN LEFT(ITM.ITMREF_0, CHARINDEX('_', ITM.ITMREF_0) - 1)
             ELSE ITM.ITMREF_0
        END AS ARTICLE_BASE,
        CASE WHEN CHARINDEX('_', ITM.ITMREF_0) > 0
             THEN SUBSTRING(ITM.ITMREF_0, CHARINDEX('_', ITM.ITMREF_0) + 1, 50)
             ELSE NULL
        END AS VARIANT_VAL
) AS SPLIT

INNER JOIN X3_LCS.BPCUSTOMER BPC ON SOH.BPCORD_0 = BPC.BPCNUM_0
LEFT  JOIN X3_LCS.BPCUSTOMER BPC_INV ON SOH.BPCINV_0 = BPC_INV.BPCNUM_0
INNER JOIN X3_LCS.BPADDRESS BPA
        ON BPC.BPCNUM_0 = BPA.BPANUM_0
       AND BPA.BPAADD_0 = SOH.BPAADD_0
LEFT  JOIN X3_LCS.SALESREP REP1 ON BPC.REP_0 = REP1.REPNUM_0
LEFT  JOIN X3_LCS.SALESREP REP2 ON BPC.REP_1 = REP2.REPNUM_0
LEFT  JOIN X3_LCS.ATEXTRA ATX
        ON ATX.IDENT2_0  = BPC.TSCCOD_2
       AND ATX.CODFIC_0  = 'ATABDIV' AND ATX.LANGUE_0  = 'FRA'
       AND ATX.ZONE_0    = 'LNGDES'  AND ATX.IDENT1_0  = '32'
LEFT  JOIN X3_LCS.ATEXTRA ATX4
        ON ATX4.IDENT2_0 = BPC.ZGROUPIND_0
       AND ATX4.CODFIC_0 = 'ATABDIV' AND ATX4.LANGUE_0 = 'FRA'
       AND ATX4.ZONE_0   = 'LNGDES'  AND ATX4.IDENT1_0 = '6021'
LEFT  JOIN X3_LCS.ATEXTRA ATX5
        ON ATX5.CODFIC_0 = 'TABLINCFG'
       AND ATX5.LANGUE_0 = 'FRA'
       AND ATX5.IDENT1_0 = ITM.CFGLIN_0
LEFT  JOIN X3_LCS.ATEXTRA ATX7
        ON ATX7.IDENT2_0  = BPC.TSCCOD_4
       AND ATX7.CODFIC_0  = 'ATABDIV' AND ATX7.LANGUE_0  = 'FRA'
       AND ATX7.ZONE_0    = 'LNGDES'  AND ATX7.IDENT1_0  = '34'
LEFT  JOIN X3_LCS.ZITMCOL ITC
        ON ITC.ITMREF_0  = SPLIT.ARTICLE_BASE
       AND ITC.YCOLLECT_0 = SOQ.YCOLLECT_0

WHERE
    SOH.ZSOHVALSTA_0 <> 3
    AND BPC.BCGCOD_0 <> 'INTER'
    AND ATX.TEXTE_0 NOT IN ('E-COMMERCE', 'RETAIL')
    {{WHERE_CLAUSE}}
