SELECT
    SDD.SDHNUM_0                        AS N_LIVRAISON,
    SDD.ITMREF_0                        AS ARTICLE,
    SDD.ITMDES_0                        AS DESIGNATION,
    SDD.QTY_0    AS QUANTITE_A_LIVREE
FROM X3_LCS.SDELIVERYD SDD
WHERE SDD.SDHNUM_0 = '{{NUMERO_LIVRAISON}}'
  AND SDD.QTYSTU_0 - SDD.RCPQTYSTU_0 > 0
ORDER BY SDD.ITMREF_0
