SELECT
    COLLECTION,
    ARTICLE,
    CODE_VARIANT,
    FAMILLE,
    GENRE,
    ITEM_GROUP,
    DESIGNATION_MODELE,
    CASE WHEN SUM(STOCK_TERME) <= 0 THEN 0 ELSE SUM(STOCK_TERME) END AS STOCK_TERME,
    AVG(PRIX) AS PRIX,
    DEVISE,
    GROUPE_TARIF
FROM [MASTER_TABLES].[EXCESS_FOR_SALES]
WHERE 1=1 {{WHERE_CLAUSE}}
  AND SITE = 'WLOGM'
  AND STATUT = 'A1'
GROUP BY
    COLLECTION,
    ARTICLE,
    CODE_VARIANT,
    FAMILLE,
    GENRE,
    ITEM_GROUP,
    DESIGNATION_MODELE,
    DEVISE,
    GROUPE_TARIF
