SELECT
    COLLECTION,
    ARTICLE,
    CODE_VARIANT,
    FAMILLE,
    GENRE,
    ITEM_GROUP,
    DESIGNATION_MODELE,
    STOCK_TERME,
    PRIX,
    DEVISE,
    GROUPE_TARIF
FROM [MASTER_TABLES].[EXCESS_FOR_SALES_TST]
