SELECT

    SID.CPY_0           AS SOCIETE,
    SIH.CRYNAM_0        AS PAYS,
    CONVERT(varchar(10), SIH.ACCDAT_0, 23) AS DATE_FACTURE,
    SID.NUM_0           AS NUM_FACTURE,
    SID.SDHNUM_0        AS SDP_CLIENT,
    SIH.GTE_0           AS GTE,
    SIV.INVTYP_0        AS INVTYP,
    SIV.SIVTYP_0        AS SIVTYP,
    TYP.TEXTE_0         AS SIVTYP_LIBELLE,
    SIV.CNOREN_0        AS MOTIF_AVOIR_CODE,
    MOT.TEXTE_0         AS MOTIF_AVOIR_LIBELLE,
    SIV.INVREF_0        AS REFERENCE_FACTURE,
    SID.CREUSR_0        AS UTILISATEUR_CREATION,
    SIV.REP_0           AS REPRESENTANT,
    SIV.BPCORD_0        AS CLIENT_COMMANDE,
    SIH.BPRPAY_0        AS TIERS_PAYEUR,
    SIH.BPRNAM_0        AS RAISON_SOCIALE,
    ATX4.TEXTE_0    AS INDEPENDANT_GROUPMENT,
    ITM.TSICOD_0        AS GENRE,
    ITM.TCLCOD_0        AS FAMILLE,
    SID.YCOLLECT_0      AS COLLECTION,
    SID.ITMREF_0        AS ARTICLE,
    CASE WHEN ITM.ZNOOSFLG_0 = 2 THEN 'Oui' ELSE 'Non' END AS NOOS,
    SID.ITMDES_0        AS DESIGNATION,
    SID.QTY_0           AS QTE,
    SIV.CUR_0           AS DEVISE_FACTURE,
    SID.NETPRI_0        AS PRIX_NET,
    SID.NETPRINOT_0     AS PRIX_NET_HT,
    SID.AMTNOTLIN_0     AS MONTANT_HT,
    SIH.RATMLT_0        AS TAUX,
    SIH.STA_0           AS ETAT
FROM X3_LCS.SINVOICED SID
         INNER JOIN X3_LCS.SINVOICE  SIH ON SIH.NUM_0 = SID.NUM_0
         INNER JOIN X3_LCS.SINVOICEV SIV ON SIV.NUM_0 = SID.NUM_0
         LEFT JOIN X3_LCS.ITMMASTER ITM ON SID.ITMREF_0 = ITM.ITMREF_0
         LEFT  JOIN X3_LCS.BPCUSTOMER BPC ON SIV.BPCORD_0 = BPC.BPCNUM_0
         LEFT  JOIN X3_LCS.ATEXTRA ATX4 ON ATX4.IDENT2_0 = BPC.ZGROUPIND_0 AND ATX4.CODFIC_0 = 'ATABDIV' AND ATX4.LANGUE_0 = 'FRA' AND ATX4.ZONE_0 = 'LNGDES' AND ATX4.IDENT1_0 = '6021'
    OUTER APPLY (
    SELECT TOP 1 ATX.TEXTE_0
    FROM X3_LCS.ATEXTRA ATX
    WHERE ATX.CODFIC_0 = 'TABSIVTYP' AND ATX.ZONE_0 = 'DESAXX' AND ATX.LANGUE_0 = 'FRA'
      AND ATX.IDENT1_0 = SIV.SIVTYP_0
) TYP
OUTER APPLY (
    SELECT TOP 1 ATX.TEXTE_0
    FROM X3_LCS.ATEXTRA ATX
    WHERE ATX.CODFIC_0 = 'ATABDIV' AND ATX.ZONE_0 = 'LNGDES' AND ATX.LANGUE_0 = 'FRA'
      AND ATX.IDENT1_0 = '8' AND ATX.IDENT2_0 = SIV.CNOREN_0
) MOT
WHERE SIV.INVTYP_0 <> 5
  AND YEAR(SIH.ACCDAT_0) = YEAR(GETDATE())
ORDER BY SIH.ACCDAT_0 DESC
