WITH sales_by_variant AS (
    SELECT
        C.ITEMFAMILYCODE AS FAMILY,
        CASE
            WHEN C.AGEGROUP = 'ADULT' THEN C.GENUSCODE
            ELSE 'KIDS'
            END AS TYPE,
        I.VARIANTCODE AS VARIANT,
        SUM(I.QUANTITY) AS QUANTITY
    FROM SEI_X3_LCS.LCS_COLLECTION C
             LEFT JOIN SEI_X3_LCS.CONSO_INVOICES I
                       ON I.ITEMNO = C.ITEM_ID
                           AND I.SERIESNO = C.SERIESCODE
    WHERE
        I.ISBOHPERIMETERPRODUCT = 1
      AND I.DOCUMENTTYPE IN ('INVOICE', 'CREDITMEMO')
      AND C.ITEMFAMILYCODE IN ('FTW', 'APL')
      AND I.COMPANYCODE = 'LCSI'
      AND C.SERIESCODE >= '2023-01-SS'
      AND I.VARIANTCODE <> 'SPL'
    {{COLLECTION_WHERE}}
    {{FAMILY_WHERE}}
    {{TYPE_WHERE}}
GROUP BY
    C.ITEMFAMILYCODE,
    CASE
    WHEN C.AGEGROUP = 'ADULT' THEN C.GENUSCODE
    ELSE 'KIDS'
END,
        I.VARIANTCODE
)

SELECT
    FAMILY,
    TYPE,
    VARIANT,
    QUANTITY,
    SUM(QUANTITY) OVER (PARTITION BY FAMILY, TYPE) AS TOTAL_FAMILY_TYPE,
    CAST(1.0 * QUANTITY / NULLIF(SUM(QUANTITY) OVER (PARTITION BY FAMILY, TYPE), 0) AS DECIMAL(10,4) ) AS WEIGHT_PERCENT
FROM sales_by_variant
ORDER BY
    FAMILY ASC,
    TYPE ASC,
    VARIANT ASC;
