SELECT
    ZIC.YCOLLECT_0               AS YCOLLECT,
    ITM_ENFANT.TCLCOD_0          AS FAMILLE,
    ENFANT.ITMREF_0              AS ARTICLE
FROM X3_LCS.YMATRITM AS ENFANT
 INNER JOIN X3_LCS.ITMMASTER ITM_ENFANT
            ON  ITM_ENFANT.ITMREF_0 = ENFANT.ITMREF_0
                AND ENFANT.YARTGEN_0   <> ''
                AND ENFANT.YARTGEN_0   IS NOT NULL
                AND CHARINDEX('_SMS', ENFANT.ITMREF_0) = 0
 INNER JOIN X3_LCS.ITMMASTER ITM_PERE
            ON  ITM_PERE.ITMREF_0   = ENFANT.YARTGEN_0
                AND ITM_PERE.ZSHOPIFY_0 <> 2
 INNER JOIN X3_LCS.ZITMCOL ZIC
            ON  ZIC.ITMREF_0 = ENFANT.YARTGEN_0;
