SELECT DISTINCT
    PTD.RCPDAT_0    AS DATE_RECEPTION,
    PTD.POHNUM_0    AS NUM_POP,
    PTD.ITMREF_0    AS ARTICLE,
    SUM(PTD.QTYUOM_0) AS QUANTITE,
    PTD.PRHFCY_0    AS SITE,
    ITM.TSICOD_0    AS CODE_MARQUE
FROM X3_LCS.PRECEIPT   AS PTH
         INNER JOIN X3_LCS.PRECEIPTD AS PTD ON PTH.PTHNUM_0 = PTD.PTHNUM_0
         INNER JOIN X3_LCS.ITMMASTER AS ITM ON PTD.ITMREF_0 = ITM.ITMREF_0
GROUP BY
    PTD.RCPDAT_0,
    PTD.POHNUM_0,
    PTD.ITMREF_0,
    PTD.PRHFCY_0,
    ITM.TSICOD_0
ORDER BY PTD.RCPDAT_0 ASC;
