WITH CollectionRecente AS (
    SELECT
        YIL.ITMREF_0,
        YCO.YCOLLECT_0,
        YCO.YDATDEB_0,
        ROW_NUMBER() OVER (
            PARTITION BY YIL.ITMREF_0
            ORDER BY YCO.YDATDEB_0 DESC
        ) AS rn
    FROM X3_LCS.YITMCOLLECT YIL
             INNER JOIN X3_LCS.YCOLLECTION YCO
                        ON YIL.YCOLLECT_0 = YCO.YCOLLECT_0
)

SELECT DISTINCT
    PTD.PRHFCY_0    AS SITE,
    CONVERT(varchar(10), PTD.RCPDAT_0, 23)  AS DATE_RECEPTION,
    PTD.POHNUM_0,
    ITM.TCLCOD_0 AS FAMILLE,
    CR.YCOLLECT_0 as COLLECTION,
    ITM.TSICOD_0    AS GENRE,
    PTD.ITMREF_0    AS ARTICLE,
    SUM(PTD.QTYUOM_0) AS QUANTITE
FROM X3_LCS.PRECEIPT   AS PTH
         INNER JOIN X3_LCS.PRECEIPTD AS PTD ON PTH.PTHNUM_0 = PTD.PTHNUM_0
         INNER JOIN X3_LCS.ITMMASTER AS ITM ON PTD.ITMREF_0 = ITM.ITMREF_0
         LEFT JOIN CollectionRecente CR ON ITM.ITMREF_0 = CR.ITMREF_0 AND CR.rn = 1
GROUP BY
    CONVERT(varchar(10), PTD.RCPDAT_0, 23),
    PTD.POHNUM_0,
    PTD.ITMREF_0,
    PTD.PRHFCY_0,
    ITM.TSICOD_0,
    CR.YCOLLECT_0,
    ITM.TCLCOD_0
ORDER BY CONVERT(varchar(10), PTD.RCPDAT_0, 23) ASC;
