WITH base AS (
    SELECT
        REP2.REPNAM_0       AS SALESMANN1,
        REP1.REPNAM_0       AS SALESMANN2,
        ATX.TEXTE_0         AS BUSINESS_MODEL,
        ATX2.TEXTE_0        AS REPORTING_DIMENSION,
        ATX3.TEXTE_0        AS DISTRIBUTION_CHANNEL,
        ATX5.TEXTE_0        AS GROUP_CODE,
        BPC.ZSOUSGROUPE_0   AS SOUS_GROUP_CODE,
        ATX4.TEXTE_0        AS INDEPENDANT_GROUPMENT,
        BPC.BPCNUM_0        AS CUSTOMER_CODE,
        BPA.CTY_0           AS CITY,
        BPC.BPCNAM_0        AS CUSTOMER_NAME,
        F.ITEMFAMILYCODE    AS FAMILY,
        CASE
            WHEN F.ITEMFAMILYCODE = 'HDW' THEN ''
            WHEN C.AGEGROUP = 'ADULT'     THEN C.GENUSCODE
            ELSE 'KIDS'
            END AS GENDER,

        SUM(CASE WHEN S.SALESORDERTYPE = 'PS' AND S.SERIESNO = '2025-01-SS' THEN S.BOH_AMOUNTEUR ELSE 0 END) AS PS_SS25,
        SUM(CASE WHEN S.SALESORDERTYPE = 'PS' AND S.SERIESNO = '2026-01-SS' THEN S.BOH_AMOUNTEUR ELSE 0 END) AS PS_SS26,
        SUM(CASE WHEN S.SALESORDERTYPE = 'PS' AND S.SERIESNO = '2027-01-SS' THEN S.BOH_AMOUNTEUR ELSE 0 END) AS PS_SS27,
        SUM(CASE WHEN S.SALESORDERTYPE = 'PS'
            AND S.SERIESNO = '2026-01-SS'
            AND S.ORDERCREATIONDATE <= DATEADD(YEAR, -1, CAST(GETDATE() - 1 AS DATE))
                     THEN S.BOH_AMOUNTEUR ELSE 0 END) AS PS_SS26_TD,

        COALESCE(SIS.SIMPLE_STATUS, 'OPEN') AS SIMPLE_STATUS,
        COALESCE(SIS.FORECAST,      0)      AS FORECAST,
        COALESCE(SIS.TARGET,        0)      AS TARGET,
        '2027-01-SS'                        AS SERIESNO_TARGET

    FROM X3_LCS.BPCUSTOMER BPC
             LEFT JOIN X3_LCS.SALESREP REP1 ON BPC.REP_0 = REP1.REPNUM_0
             LEFT JOIN X3_LCS.SALESREP REP2 ON BPC.REP_1 = REP2.REPNUM_0
             LEFT JOIN X3_LCS.ATEXTRA ATX  ON ATX.IDENT2_0  = BPC.TSCCOD_2    AND ATX.CODFIC_0  = 'ATABDIV' AND ATX.LANGUE_0  = 'FRA' AND ATX.ZONE_0  = 'LNGDES' AND ATX.IDENT1_0  = '32'
             LEFT JOIN X3_LCS.ATEXTRA ATX2 ON ATX2.IDENT2_0 = BPC.TSCCOD_3    AND ATX2.CODFIC_0 = 'ATABDIV' AND ATX2.LANGUE_0 = 'FRA' AND ATX2.ZONE_0 = 'LNGDES' AND ATX2.IDENT1_0 = '33'
             LEFT JOIN X3_LCS.ATEXTRA ATX3 ON ATX3.IDENT2_0 = BPC.TSCCOD_4    AND ATX3.CODFIC_0 = 'ATABDIV' AND ATX3.LANGUE_0 = 'FRA' AND ATX3.ZONE_0 = 'LNGDES' AND ATX3.IDENT1_0 = '34'
             LEFT JOIN X3_LCS.ATEXTRA ATX4 ON ATX4.IDENT2_0 = BPC.ZGROUPIND_0 AND ATX4.CODFIC_0 = 'ATABDIV' AND ATX4.LANGUE_0 = 'FRA' AND ATX4.ZONE_0 = 'LNGDES' AND ATX4.IDENT1_0 = '6021'
             LEFT JOIN X3_LCS.ATEXTRA ATX5 ON ATX5.IDENT2_0 = BPC.ZGRPCOD_0 AND ATX5.CODFIC_0 = 'ATABDIV' AND ATX5.LANGUE_0 = 'FRA' AND ATX5.ZONE_0 = 'LNGDES' AND ATX5.IDENT1_0 = '6028'
             LEFT JOIN X3_LCS.BPADDRESS BPA ON BPC.BPCNUM_0 = BPA.BPANUM_0

             CROSS JOIN (SELECT DISTINCT ITEMFAMILYCODE FROM SEI_X3_LCS.LCS_COLLECTION) F

             LEFT JOIN SEI_X3_LCS.LCS_COLLECTION C
                       ON C.ITEMFAMILYCODE = F.ITEMFAMILYCODE
             LEFT JOIN SEI_X3_LCS.LCS_X3SALESX S
                       ON S.SERIESNO   = C.SERIESCODE
                           AND S.ITEMNO     = C.ITEM_ID
                           AND S.CUSTOMERNO = BPC.BPCNUM_0

             LEFT JOIN {{TABLE_SELL_IN_SUIVI_PS}} SIS
ON SIS.CUSTOMER_CODE = BPC.BPCNUM_0
    AND SIS.CITY          = COALESCE(BPA.CTY_0, '')
    AND SIS.FAMILY        = F.ITEMFAMILYCODE
    AND SIS.GENDER        = CASE
    WHEN F.ITEMFAMILYCODE = 'HDW' THEN ''
    WHEN C.AGEGROUP = 'ADULT'     THEN C.GENUSCODE
    ELSE 'KIDS'
END
AND SIS.SERIESNO      = '2027-01-SS'

    WHERE 1=1
      AND S.SERIESNO  >= '2025-01-SS'
      AND BPC.TSCCOD_2 = '01'
      AND F.ITEMFAMILYCODE IN ('FTW', 'HDW', 'APL')
    AND BPA.BPAADD_0 = '001'

    GROUP BY
        REP2.REPNAM_0, REP1.REPNAM_0, ATX.TEXTE_0, ATX2.TEXTE_0, ATX3.TEXTE_0,
        BPC.ZSOUSGROUPE_0, ATX4.TEXTE_0, BPC.BPCNUM_0, BPA.CTY_0, BPC.BPCNAM_0,
        F.ITEMFAMILYCODE,
        CASE
            WHEN F.ITEMFAMILYCODE = 'HDW' THEN ''
            WHEN C.AGEGROUP = 'ADULT'     THEN C.GENUSCODE
            ELSE 'KIDS'
END,
        SIS.SIMPLE_STATUS, SIS.FORECAST, SIS.TARGET, ATX5.TEXTE_0
)
SELECT
    SALESMANN1, SALESMANN2, BUSINESS_MODEL, REPORTING_DIMENSION, DISTRIBUTION_CHANNEL,
    GROUP_CODE, SOUS_GROUP_CODE, INDEPENDANT_GROUPMENT, CUSTOMER_CODE, CITY, CUSTOMER_NAME,
    FAMILY, GENDER,
    SERIESNO_TARGET AS SERIESNO,
    SIMPLE_STATUS, FORECAST, TARGET,

    PS_SS25 AS PS_ORDER_SS25_EOS,
    PS_SS26 AS PS_ORDER_SS26_EOS,
    PS_SS27 AS PS_ORDER_SS27_TD,
    PS_SS26_TD AS PS_ORDER_SS26_TD,

    ISNULL(PS_SS27 / NULLIF(PS_SS26_TD, 0), 0) - 1 AS VS_LY_TD,

    CASE WHEN SIMPLE_STATUS = 'COMPLETE' AND PS_SS26 > 0 AND PS_SS27 > 0
             THEN PS_SS27 ELSE 0 END AS SS27_TD_LFL_COMPLETE,

    CASE WHEN SIMPLE_STATUS = 'COMPLETE' AND PS_SS26 > 0 AND PS_SS27 > 0
             THEN PS_SS26 ELSE 0 END AS SS26_EOS_LFL,

    ISNULL(
        (CASE WHEN SIMPLE_STATUS = 'COMPLETE' AND PS_SS26 > 0 AND PS_SS27 > 0 THEN PS_SS27 ELSE 0 END)
            / NULLIF(CASE WHEN SIMPLE_STATUS = 'COMPLETE' AND PS_SS26 > 0 AND PS_SS27 > 0 THEN PS_SS26 ELSE 0 END, 0)
        , 0) - 1 AS COMPLETE_VS_LY_LFL_EOS,

    CASE
        WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27
        ELSE CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
        END AS LANDING_FCST,

    ISNULL(
        (CASE
             WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27
             ELSE CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
            END) / NULLIF(PS_SS26, 0), 0) AS VS_SS26_EOS,

    (CASE
         WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27
         ELSE CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
        END) - PS_SS27 AS TOGO_VS_FCST_EN_VALO,

    (CASE
         WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27
         ELSE CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
        END) - TARGET AS FCST_VS_TARGET_EN_VALO,

    CASE WHEN PS_SS27 = 0 AND SIMPLE_STATUS = 'COMPLETE' AND PS_SS26 > 0
             THEN PS_SS26 ELSE 0 END AS SS26_EOS_VALO_COMPLETE,

    CASE WHEN PS_SS27 = 0 AND SIMPLE_STATUS = 'COMPLETE' AND PS_SS26 > 0
             THEN 1 ELSE 0 END AS CUST,

    CASE WHEN SIMPLE_STATUS = 'OPEN' THEN PS_SS26 ELSE 0 END AS TTL_PS_LY,
    CASE WHEN SIMPLE_STATUS = 'OPEN' AND PS_SS26 > 0 THEN 1 ELSE 0 END AS CUST_OPEN,

    CASE
        WHEN SIMPLE_STATUS = 'OPEN' THEN
            CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
        ELSE 0
        END AS FCST_REPS,

    0  AS LW_FCST_REPS,
    '' AS VS_LW,

    ISNULL(
        (CASE
             WHEN SIMPLE_STATUS = 'OPEN' THEN
                 CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
             ELSE 0
            END)
            / NULLIF(CASE WHEN SIMPLE_STATUS = 'OPEN' THEN PS_SS26 ELSE 0 END, 0), 0) - 1 AS FCST_SALES_VS_EOS_SS26,

    (CASE
         WHEN SIMPLE_STATUS = 'OPEN' THEN
             CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
         ELSE 0
        END)
        + (CASE WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27 ELSE 0 END) AS FCST_SS27_LFL,

    (CASE
         WHEN SIMPLE_STATUS = 'OPEN' THEN
             CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
         ELSE 0
        END)
        + (CASE WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27 ELSE 0 END)
        - (CASE
               WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27
               ELSE CASE WHEN PS_SS27 > FORECAST THEN PS_SS27 ELSE FORECAST END
        END) AS DIFF,

    CASE WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27 ELSE 0 END AS SS27_COMPLETE,
    CASE WHEN SIMPLE_STATUS = 'COMPLETE' AND PS_SS27 > 0 THEN PS_SS26 ELSE 0 END AS LY_COMPLETE_EOS,

    ISNULL(
        (CASE WHEN SIMPLE_STATUS = 'COMPLETE' THEN PS_SS27 ELSE 0 END)
            / NULLIF(CASE WHEN SIMPLE_STATUS = 'COMPLETE' AND PS_SS27 > 0 THEN PS_SS26 ELSE 0 END, 0), 0) - 1 AS EVO_COMPLETE_VS_LY,

    0  AS BOH_FIGE_LW,
    '' AS EVO_BOH_VS_LW

FROM base
ORDER BY FAMILY, CUSTOMER_NAME;
