WITH sto_agg AS (
    SELECT
        STOFCY_0,
        ITMREF_0,
        STA_0,
        SUM(QTYSTU_0) AS STOCK_INTERNE,
        SUM(PRIVAL_0 * QTYSTU_0) AS VALORISATION_STOCK_INTERNE
    FROM X3_LCS.STOJOU
    WHERE CAST(IPTDAT_0 AS DATE) <= CAST(GETDATE() AS DATE)
    GROUP BY STOFCY_0, ITMREF_0, STA_0
)

SELECT
    STK.STOFCY_0 AS SITE,
    STK.STA_0 AS STATUS_STOCK,

    SUM(STK.QTYSTU_0) AS STOCK_INTERNE,

    SUM(s.VALORISATION_STOCK_INTERNE) AS VALORISATION_STOCK_INTERNE,

    CASE
        WHEN STK.STA_0 = 'A1' THEN 0
        WHEN STK.STA_0 = 'A2' THEN 0.5
        WHEN STK.STA_0 = 'A3'  THEN 1
        ELSE 0
        END AS TAUX_DEPRECIATION,

    SUM(ISNULL(s.VALORISATION_STOCK_INTERNE,0)) *
    CASE
        WHEN STK.STA_0 = 'A1' THEN 1
        WHEN STK.STA_0 = 'A2' THEN 0.5
        ELSE 0
        END AS VALEUR_REEVALUATION

FROM X3_LCS.STOCK STK
INNER JOIN X3_LCS.ITMMASTER ITM ON ITM.ITMREF_0 = STK.ITMREF_0
left join sto_agg s ON s.ITMREF_0 = STK.ITMREF_0 AND s.STOFCY_0 = STK.STOFCY_0 AND s.STA_0 = STK.STA_0

WHERE STK.STOFCY_0 IS NOT NULL
    {{FAMILLE_WHERE}}

GROUP BY STK.STOFCY_0, STK.STA_0
ORDER BY VALEUR_REEVALUATION DESC;
