SELECT
    ARTICLE,

    -- Stock LOGTEX (site WLOGM uniquement)
    SUM(CASE WHEN SITE = 'WLOGM' THEN STOCK_INTERNE ELSE 0 END) AS STOCK_INTERNE_LOGTEX,

    -- Stock MAGASIN (agrégation des sites magasins)
    SUM(CASE WHEN SITE IN (
                           'RBBAY','RBCAB','RBCAG','RBCIT','RBORL','RBSJL','RBSTG',
                           'RFMIR','RFROP','RFROU','RFTRO','RFVIL','RPOP1','RPOP2'
        ) THEN STOCK_INTERNE ELSE 0 END) AS STOCK_INTERNE_MAGASIN

FROM [SEICube].[MASTER_TABLES].[STOCK_ALLOCATION] s

WHERE
    s.STATUS_STOCK = 'A1'
  AND s.SITE IN (
    'WLOGM',
    'RBBAY','RBCAB','RBCAG','RBCIT','RBORL','RBSJL','RBSTG',
    'RFMIR','RFROP','RFROU','RFTRO','RFVIL','RPOP1','RPOP2'
    )

GROUP BY ARTICLE
HAVING
    SUM(CASE WHEN SITE = 'WLOGM' THEN STOCK_INTERNE ELSE 0 END) <> 0
    OR SUM(CASE WHEN SITE IN (
    'RBBAY','RBCAB','RBCAG','RBCIT','RBORL','RBSJL','RBSTG',
    'RFMIR','RFROP','RFROU','RFTRO','RFVIL','RPOP1','RPOP2'
    ) THEN STOCK_INTERNE ELSE 0 END) <> 0;
