SELECT
    STK.STOFCY_0 AS SITE,
    STK.STA_0 AS STATUS_STOCK,

    SUM(STK.QTYSTU_0) AS STOCK_INTERNE,

    0 AS VALORISATION_STOCK_INTERNE,

    CASE
        WHEN STK.STA_0 = 'A1' THEN 0
        WHEN STK.STA_0 = 'A2' THEN 0.5
        WHEN STK.STA_0 = 'R'  THEN 1
        ELSE 0
        END AS TAUX_DEPRECIATION,

    0 *
    CASE
        WHEN STK.STA_0 = 'A1' THEN 0
        WHEN STK.STA_0 = 'A2' THEN 0.5
        WHEN STK.STA_0 = 'R'  THEN 1
        ELSE 0
        END AS VALEUR_REEVALUATION

FROM X3_LCS.STOCK STK
         INNER JOIN X3_LCS.ITMMASTER ITM ON ITM.ITMREF_0 = STK.ITMREF_0

WHERE STK.STOFCY_0 IS NOT NULL
    {{FAMILLE_WHERE}}

GROUP BY STK.STOFCY_0, STK.STA_0;
