SELECT
    STK.STOFCY_0 as SITE,
    FCY.FCYNAM_0 as DESCRIPTION_SITE,
    ITM.TCLCOD_0 as FAMILLE,
    YIL.YCOLLECT_0 as DERNIERE_COLLECTION,
    ITM.ITMREF_0 as ARTICLE,
    ITM.ITMDES1_0 as DESCRIPTION_ARTICLE,
    STK.STA_0 as STATUS_STOCK,
    STK.QTYSTU_0 as STOCK_INTERNE,
    0 as VALORISATION_STOCK_INTERNE,
    case when STK.STA_0 = 'A' then ITV.PHYALL_0 else 0 end as STOCK_ALLOUE,
    0 as VALORISATION_STOCK_ALLOUE,
    case when STK.STA_0 = 'A' then (STK.QTYSTU_0 - ITV.PHYALL_0) else STK.QTYSTU_0 end as STOCK_DISPONIBLE,
    0 as VALORISATION_STOCK_DISPONIBLE,
    case when STK.STA_0 = 'A' then ITV.GLOALL_0 else 0 end as STOCK_RESERVE,
    0 as VALORISATION_STOCK_RESERVE,
    case when STK.STA_0 = 'A' then (STK.QTYSTU_0 - ITV.PHYALL_0 - ITV.GLOALL_0) else STK.QTYSTU_0 end as STOCK_REEL,
    0 as VALORISATION_STOCK_REEL
FROM X3_LCS.ITMMASTER ITM
LEFT JOIN X3_LCS.YITMCOLLECT YIL ON ITM.ITMREF_0 = YIL.ITMREF_0
INNER JOIN X3_LCS.YCOLLECTION YCO ON YIL.YCOLLECT_0 = YCO.YCOLLECT_0
LEFT JOIN X3_LCS.ITMMVT ITV ON ITM.ITMREF_0 = ITV.ITMREF_0
LEFT JOIN X3_LCS.STOCK STK ON ITM.ITMREF_0 = STK.ITMREF_0 AND ITV.STOFCY_0 = STK.STOFCY_0
LEFT JOIN X3_LCS.FACILITY FCY ON STK.STOFCY_0 = FCY.FCY_0
WHERE ITM.ITMREF_0 IS NOT NULL
AND STK.STOFCY_0 IS NOT NULL
  and YCO.YDATDEB_0 <= CAST(GETDATE() AS date)
  AND YCO.YDATFIN_0 >= CAST(GETDATE() AS date)
