
WITH
    CollectionRecente AS (
        SELECT
            YIL.ITMREF_0,
            YCO.YCOLLECT_0,
            YCO.YDATDEB_0,
            ROW_NUMBER() OVER (
            PARTITION BY YIL.ITMREF_0
            ORDER BY YCO.YDATDEB_0 DESC
        ) AS rn
        FROM X3_LCS.YITMCOLLECT YIL
                 INNER JOIN X3_LCS.YCOLLECTION YCO
                            ON YIL.YCOLLECT_0 = YCO.YCOLLECT_0
    )

SELECT [SITE]
    ,[DESCRIPTION_SITE]
    ,[FAMILLE]
    ,CR.YCOLLECT_0 AS DERNIERE_COLLECTION
    ,[ARTICLE]
    ,[DESCRIPTION_ARTICLE]
    ,[STATUT]
    ,[STOCK_INTERNE]
    ,[ACHAT_M0]
    ,[VENTE_M0]
    ,ISNULL(RESA_ETAIL_M0,0) as RESA_ETAIL_M0
    ,ISNULL(RESA_RETAIL_M0,0) as RESA_RETAIL_M0
    ,[STOCK_TERME_M0]
    ,[ACHAT_M1]
    ,[VENTE_M1]
    ,ISNULL(RESA_ETAIL_M1,0) as RESA_ETAIL_M1
    ,ISNULL(RESA_RETAIL_M1,0) as RESA_RETAIL_M1
    ,[STOCK_TERME_M1]
    ,[ACHAT_M2]
    ,[VENTE_M2]
    ,ISNULL(RESA_ETAIL_M2,0) as RESA_ETAIL_M2
    ,ISNULL(RESA_RETAIL_M2,0) as RESA_RETAIL_M2
    ,[STOCK_TERME_M2]
    ,[ACHAT_M3]
    ,[VENTE_M3]
    ,ISNULL(RESA_ETAIL_M3,0) as RESA_ETAIL_M3
    ,ISNULL(RESA_RETAIL_M3,0) as RESA_RETAIL_M3
    ,[STOCK_TERME_M3]
    ,[ACHAT_M4]
    ,[VENTE_M4]
    ,ISNULL(RESA_ETAIL_M4,0) as RESA_ETAIL_M4
    ,ISNULL(RESA_RETAIL_M4,0) as RESA_RETAIL_M4
    ,[STOCK_TERME_M4]
    ,[ACHAT_M5]
    ,[VENTE_M5]
    ,ISNULL(RESA_ETAIL_M5,0) as RESA_ETAIL_M5
    ,ISNULL(RESA_RETAIL_M5,0) as RESA_RETAIL_M5
    ,[STOCK_TERME_M5]
    ,[ACHAT_M6]
    ,[VENTE_M6]
    ,ISNULL(RESA_ETAIL_M6,0) as RESA_ETAIL_M6
    ,ISNULL(RESA_RETAIL_M6,0) as RESA_RETAIL_M6
    ,[STOCK_TERME_M6]
FROM [SEICube].[MASTER_TABLES].[PRODXXX_V_STOCK_TERME_6MOIS] s
    LEFT JOIN CollectionRecente CR
ON s.ARTICLE = CR.ITMREF_0
    AND CR.rn = 1
