SELECT
    REP1.REPNAM_0                  AS REPRESENTANT,
    MAX(REP2.REPNAM_0)             AS MANAGER_RZ,
    SUM(CASE WHEN S.SALESORDERTYPE = 'PS' AND S.SERIESNO = '2026-01-SS' THEN S.BOH_AMOUNTEUR ELSE 0 END) AS PS_SS26,
    SUM(CASE WHEN S.SALESORDERTYPE = 'PS' AND S.SERIESNO = '2027-01-SS' THEN S.BOH_AMOUNTEUR ELSE 0 END) AS PS_SS27,
    COALESCE(MAX(OBJ.OBJECTIF), 0) AS OBJECTIF_PS_SS27
FROM SEI_X3_LCS.LCS_X3SALESX S
LEFT JOIN X3_LCS.BPCUSTOMER BPC ON S.CUSTOMERNO = BPC.BPCNUM_0
LEFT JOIN X3_LCS.SALESREP REP1  ON BPC.REP_0 = REP1.REPNUM_0
LEFT JOIN X3_LCS.SALESREP REP2  ON BPC.REP_1 = REP2.REPNUM_0
LEFT JOIN X3_LCS.ITMMASTER ITM  ON S.ITEMNO = ITM.ITMREF_0
INNER JOIN [SEICube].[MASTER_TABLES].[SUIVI_PERF_WHOLESALE_FR] OBJ
    ON OBJ.REPRESENTANT = REP1.REPNAM_0 AND OBJ.SERIESNO = '2027-01-SS'
WHERE S.SALESORDERTYPE = 'PS'
  AND ITM.TCLCOD_0 IN ('FTW', 'HDW', 'APL')
  AND S.SERIESNO IN ('2026-01-SS', '2027-01-SS')
  AND REP1.REPNAM_0 IS NOT NULL
GROUP BY REP1.REPNAM_0
ORDER BY MAX(REP2.REPNAM_0), REP1.REPNAM_0
