SELECT CONVERT(varchar(10), [Date Création], 23) AS [Date Création]
      ,[Type Commande]
      ,[Commande]
      ,[Ligne]
      ,[Séquence]
      ,[Article]
      ,[Statut Ligne]
      ,[Reference Interne]
      ,[Bon de Préparation]
      ,[Statut Bon de Préparation]
      ,[Statut PREPS]
      ,[Log Envoyé]
      ,CONVERT(varchar(10), [DATE_RETOUR], 23) AS [DATE_RETOUR]
      ,[Etat commande]
      ,[Reference Commande]
      ,[Numéro Tracking]
  FROM [MASTER_TABLES].[IT0005B_Suivi_Commandes_Web]
