SELECT
    CUST.COUNTRYCODE,
    MONTH(I.DOCUMENTPOSTINGDATE) AS MOIS,
    CASE WHEN CUST.BILLTONAME = 'E-Commerce - Marketplace'
         THEN CUST.CUSTOMER_NAME
         ELSE CUST.BILLTONAME
    END AS CLIENT,
    -- Meme convention que le Backlog Client : REPRESENTANT 1 est le N+1 (responsable
    -- de zone), REPRESENTANT 2 le commercial terrain. Un client regroupant plusieurs
    -- representants (ex. INTERSPORT FRANCE SA) est arbitre cote PHP lors du pivot.
    CUST.SALESMANNAMENPLUS1 AS REPRESENTANT_1,
    CUST.SALESMANNAME       AS REPRESENTANT_2,
    SUM(I.QUANTITY)    AS QUANTITE,
    SUM(I.AMOUNTEURTM) AS CA

FROM SEI_X3_LCS.CONSO_INVOICES I

LEFT JOIN SEI_X3_LCS.LCS_CUSTOMER CUST
    ON  I.COMPANYCODE = CUST.COMPANY_ID
    AND I.CUSTOMERNO  = CUST.CUSTOMER_ID

LEFT JOIN SEI_X3_LCS.LCS_COLLECTION COLL
    ON  I.ITEMNO   = COLL.ITEM_ID
    AND I.SERIESNO = COLL.SERIESCODE

WHERE
    I.ISBOHPERIMETERPRODUCT = 1
    AND (
        I.DOCUMENTTYPE IN ('INVOICE', 'CREDITMEMO')
        OR (I.DOCUMENTTYPE IN ('ORDER') AND I.ORDERSTATUS = 3 AND I.DLVQTY > 0)
    )
    AND COLL.ITEMFAMILYCODE IN ('FTW', 'HDW', 'APL')
    AND I.COMPANYCODE = 'LCSI'
    AND YEAR(I.DOCUMENTPOSTINGDATE) = {{YEAR}}
    AND CUST.MAINNETWORK IS NOT NULL

GROUP BY
    MONTH(I.DOCUMENTPOSTINGDATE),
    CASE WHEN CUST.BILLTONAME = 'E-Commerce - Marketplace'
         THEN CUST.CUSTOMER_NAME
         ELSE CUST.BILLTONAME
    END,
    CUST.COUNTRYCODE,
    CUST.SALESMANNAMENPLUS1,
    CUST.SALESMANNAME
