SELECT
    COLL.ITEMFAMILYCODE          AS FAMILLE,
    I.ITEMNO                     AS CODE_ARTICLE,
    MONTH(I.DOCUMENTPOSTINGDATE) AS MOIS,
    SUM(I.QUANTITY)              AS QUANTITE,
    SUM(I.AMOUNTEURTM)           AS CA

FROM SEI_X3_LCS.CONSO_INVOICES I

LEFT JOIN SEI_X3_LCS.LCS_CUSTOMER CUST
    ON  I.COMPANYCODE = CUST.COMPANY_ID
    AND I.CUSTOMERNO  = CUST.CUSTOMER_ID

LEFT JOIN SEI_X3_LCS.LCS_COLLECTION COLL
    ON  I.ITEMNO   = COLL.ITEM_ID
    AND I.SERIESNO = COLL.SERIESCODE

WHERE
    I.ISBOHPERIMETERPRODUCT = 1
    AND (
        I.DOCUMENTTYPE IN ('INVOICE', 'CREDITMEMO')
        OR (I.DOCUMENTTYPE IN ('ORDER') AND I.ORDERSTATUS = 3 AND I.DLVQTY > 0)
    )
    AND COLL.ITEMFAMILYCODE IN ('FTW', 'HDW', 'APL')
    AND I.COMPANYCODE = 'LCSI'
    AND YEAR(I.DOCUMENTPOSTINGDATE) = {{YEAR}}
    AND CUST.MAINNETWORK IS NOT NULL
    AND (
        CASE WHEN CUST.BILLTONAME = 'E-Commerce - Marketplace'
             THEN CUST.CUSTOMER_NAME
             ELSE CUST.BILLTONAME
        END
    ) = '{{CLIENT}}'

GROUP BY
    COLL.ITEMFAMILYCODE,
    I.ITEMNO,
    MONTH(I.DOCUMENTPOSTINGDATE)
