WITH
-- Toutes les collections NON droppées par article (pour COLLECTIONS_DISPONIBLES)
CollectionsNonDroppees AS (
    SELECT
        YIL.ITMREF_0,
        YIL.YCOLLECT_0,
        YCO.YDATDEB_0,
        ROW_NUMBER() OVER (
            PARTITION BY YIL.ITMREF_0
            ORDER BY YCO.YDATDEB_0 DESC
        ) AS rn
    FROM X3_LCS.YITMCOLLECT YIL
             INNER JOIN X3_LCS.YCOLLECTION YCO
                        ON YIL.YCOLLECT_0 = YCO.YCOLLECT_0
             LEFT JOIN X3_LCS.ZITMCOL ITC
                       ON ITC.ITMREF_0   = LEFT(YIL.ITMREF_0, CHARINDEX('_', YIL.ITMREF_0 + '_') - 1)
    AND ITC.YCOLLECT_0 = YCO.YCOLLECT_0
    WHERE ISNULL(ITC.ZDROPPED_0, 0) <> 2
)

SELECT
    COLL.ITEMFAMILYCODE          AS FAMILLE,
    I.ITEMNO                     AS CODE_ARTICLE,
    COLL.GENUSCODE AS GENRE,
    ITC.ZSEGOFF_0 AS SEG_OFFRE,
    MONTH(I.DOCUMENTPOSTINGDATE) AS MOIS,
    SUM(I.QUANTITY)              AS QUANTITE,
    SUM(I.AMOUNTEURTM)           AS CA

FROM SEI_X3_LCS.CONSO_INVOICES I

LEFT JOIN SEI_X3_LCS.LCS_CUSTOMER CUST
    ON  I.COMPANYCODE = CUST.COMPANY_ID
    AND I.CUSTOMERNO  = CUST.CUSTOMER_ID

LEFT JOIN CollectionsNonDroppees CR
    ON CR.ITMREF_0 = I.ITEMNO
    AND CR.rn = 1

LEFT JOIN SEI_X3_LCS.LCS_COLLECTION COLL
    ON  I.ITEMNO   = COLL.ITEM_ID
    AND I.SERIESNO = COLL.SERIESCODE

LEFT JOIN X3_LCS.ZITMCOL ITC
    ON ITC.ITMREF_0   = CR.ITMREF_0
    AND ITC.YCOLLECT_0 = CR.YCOLLECT_0

WHERE
    I.ISBOHPERIMETERPRODUCT = 1
    AND (
        I.DOCUMENTTYPE IN ('INVOICE', 'CREDITMEMO')
        OR (I.DOCUMENTTYPE IN ('ORDER') AND I.ORDERSTATUS = 3 AND I.DLVQTY > 0)
    )
    AND COLL.ITEMFAMILYCODE IN ('FTW', 'HDW', 'APL')
    AND I.COMPANYCODE = 'LCSI'
    AND YEAR(I.DOCUMENTPOSTINGDATE) = {{YEAR}}
    AND CUST.MAINNETWORK IS NOT NULL
    AND (
        CASE WHEN CUST.BILLTONAME = 'E-Commerce - Marketplace'
             THEN CUST.CUSTOMER_NAME
             ELSE CUST.BILLTONAME
        END
    ) = '{{CLIENT}}'

GROUP BY
    COLL.ITEMFAMILYCODE,
    I.ITEMNO,
    MONTH(I.DOCUMENTPOSTINGDATE),
    COLL.GENUSCODE,
    ITC.ZSEGOFF_0
