security:
    hide_user_not_found: false

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    role_hierarchy:
        ROLE_ADV: ROLE_USER
        ROLE_ACCOUNTING: ROLE_USER
        ROLE_LOGISTIC: ROLE_USER
        ROLE_MANAGEMENT: ROLE_USER
        ROLE_MARKETING: ROLE_USER
        ROLE_PURCHASING: ROLE_USER
        ROLE_RH: ROLE_USER
        ROLE_SALES: ROLE_USER
        ROLE_SALT: ROLE_USER
        ROLE_SAV: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_ADV, ROLE_ACCOUNTING, ROLE_LOGISTIC, ROLE_MANAGEMENT, ROLE_MARKETING, ROLE_PURCHASING, ROLE_RH, ROLE_SALES, ROLE_SALT, ROLE_SAV]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            entry_point: App\Security\AzureAuthenticator
            lazy: true
            stateless: false
            switch_user: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AzureAuthenticator
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/(fr|en)/connect, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en)/callback, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en)/admin/, roles: ROLE_ADMIN }
        - { path: ^/(fr|en)/dashboard, roles: ROLE_USER }
        - { path: ^/(fr|en)/, roles: ROLE_USER }
