SELECT * FROM intranet_lcs.aggrid_option where grid_name = 'comptes_fournisseurs_grid';
delete FROM intranet_lcs.aggrid_option where grid_name = 'comptes_fournisseurs_grid';

INSERT INTO intranet_lcs.aggrid_option
(grid_name, field, header_name, type, min_width, sortable, filter, cell_style, flex, agg_func, visible, order_index, cell_class, computed, value_formatter, comparator)
VALUES
('comptes_fournisseurs_grid','CODE_FOURNISSEUR','Code Fournisseur','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,1,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','RAISON_SOCIALE','Raison Sociale','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,2,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','CODE_PAYS_FOURNISSEUR','Code Pays Fournisseur','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,3,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','FOURNISSEUR_INTERSITE','Fournisseur Intersite','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,4,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','CODE_CONDITION_PAIEMENT','Code Condition Paiement','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,5,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','DEVISE','Devise','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,6,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','EMAIL_CONFIRMATION_COMMANDE','Email Confirmation Commande','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,7,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','NOM_CONFIRMATION_COMMANDE','Nom Confirmation Commande','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,8,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','PRENOM_CONFIRMATION_COMMANDE','Prenom Confirmation Commande','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,9,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','TEL_CONFIRMATION_COMMANDE','Tel. Confirmation Commande','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,10,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','EMAIL_AVIS_PAIEMENT','Email Avis Paiement','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,11,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','NOM_AVIS_PAIEMENT','Nom Avis Paiement','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,12,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','PRENOM_AVIS_PAIEMENT','Prenom Avis Paiement','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,13,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','TEL_AVIS_PAIEMENT','Tel. Avis Paiement','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,14,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','NUMERO_SIRET','Numero Siret','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,15,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','TVA_INTRACOMMUNAUTAIRE','TVA Intracommunautaire','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,16,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','CODE_COMPTABLE','Code Comptable','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,17,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','CODE_ADRESSE_DEFAUT','Code Adresse Defaut','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,18,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','LIBELLE_ADRESSE','Libelle Adresse','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,19,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','ADRESSE_LIGNE_1','Adresse Ligne 1','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,20,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','ADRESSE_LIGNE_2','Adresse Ligne 2','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,21,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','ADRESSE_LIGNE_3','Adresse Ligne 3','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,22,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','CODE_POSTAL','Code Postal','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,23,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','VILLE','Ville','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,24,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','ETAT_REGION','Etat Region','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,25,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','PAYS_ADRESSE','Pays Adresse','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,26,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','CODE_PAYS_ADRESSE','Code Pays Adresse','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,27,NULL,0,NULL,NULL),
('comptes_fournisseurs_grid','LANGUE','Langue','string',200,1,'agTextColumnFilter','{"fontSize": "16px", "textAlign": "left", "borderRight": "0.2px solid #CECECEFF", "borderBottom": "0.2px solid #CECECEFF"}',NULL,NULL,1,28,NULL,0,NULL,NULL);
